export const GET_SPENDINGS_REQUEST = 'GET_SPENDINGS_REQUEST'
export const GET_SPENDINGS_SUCCESS = 'GET_SPENDINGS_SUCCESS'
export const GET_SPENDINGS_FAILURE = 'GET_SPENDINGS_FAILURE'

export const ADD_SPENDING_REQUEST = 'ADD_SPENDING_REQUEST'
export const ADD_SPENDING_SUCCESS = 'ADD_SPENDING_SUCCESS'
export const ADD_SPENDING_FAILURE = 'ADD_SPENDING_FAILURE'

export const DELETE_SPENDING_REQUEST = 'DELETE_SPENDING_REQUEST'
export const DELETE_SPENDING_SUCCESS = 'DELETE_SPENDING_SUCCESS'
export const DELETE_SPENDING_FAILURE = 'DELETE_SPENDING_FAILURE'

export const EDIT_SPENDING_REQUEST = 'EDIT_SPENDING_REQUEST'
export const EDIT_SPENDING_SUCCESS = 'EDIT_SPENDING_SUCCESS'
export const EDIT_SPENDING_FAILURE = 'EDIT_SPENDING_FAILURE'
